# Generated by Django 4.2.5 on 2023-09-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
