# Generated by Django 4.2.5 on 2023-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='authors_books', to='drf_app.author'),
        ),
    ]
