# Generated by Django 4.2.5 on 2023-09-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0005_remove_author_bio_remove_book_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
