# Generated by Django 4.2.5 on 2023-09-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_app', '0006_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
